version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - gochecknoglobals
    - nonamedreturns
    - exhaustruct
    - inamedparam
    - tagliatelle
    - noinlineerr
    - exhaustive
    - varnamelen
    - depguard
    - intrange
    - ireturn
    - wsl
  settings:
    cyclop:
      max-complexity: 13
    errcheck:
      check-type-assertions: true
    funlen:
      lines: 80
      ignore-comments: true
    gocritic:
      enabled-tags:
        - performance
        - opinionated
        - diagnostic
        - style
    govet:
      enable-all: true
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    modernize:
      disable:
        - rangeint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forbidigo
        path: cmd/decompose/main\.go
      - linters:
          - errchkjson
        path: internal/builder/json\.go
      - linters:
          - govet
        path: internal/node/json\.go
        text: fieldalignment
      - linters:
          - govet
        path: internal/builder/yaml\.go
        text: fieldalignment
      - linters:
          - gosec
        path: internal/client/defaults\.go
        text: G115
      - linters:
          - gosec
        path: internal/graph/netstat\.go
        text: G115
      - linters:
          - recvcheck
        path: internal/graph/netproto\.go
      - linters:
          - dupl
          - err113
          - errcheck
          - funlen
          - gocritic
          - maintidx
        path: ._test\.go
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
