run:
  allow-parallel-runners: true
  go: '1.22'

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - exhaustivestruct
    - nonamedreturns
    - structcheck
    - tagliatelle
    - nosnakecase
    - exhaustruct
    - inamedparam
    - exhaustive
    - interfacer
    - varnamelen
    - scopelint
    - deadcode
    - depguard
    - maligned
    - varcheck
    - intrange
    - ifshort
    - ireturn
    - gofumpt
    - golint
    - gci

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
  funlen:
    lines: 80
    ignore-comments: true
  cyclop:
    max-complexity: 13
    skip-tests: true
  gocritic:
    enabled-tags:
      - performance
      - opinionated
      - diagnostic
      - style

issues:
  exclude-rules:
    - path: cmd/decompose/main\.go
      linters:
        - forbidigo
    - path: internal/builder/json\.go
      linters:
        - errchkjson
    - path: internal/node/json\.go
      text: "fieldalignment"
      linters:
        - govet # fieldalignment issue, ignored for json readability
    - path: internal/builder/yaml\.go
      text: "fieldalignment"
      linters:
        - govet # fieldalignment issue, ignored for yaml readability
    - path: ._test\.go
      linters:
        - goerr113
        - gocritic
        - errcheck
        - maintidx
        - funlen
        - dupl
