name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  update_registry:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          tags: |
            ${{ github.repository }}:${{ env.github.ref_name }}
            ${{ github.repository }}:latest
          push: true
      - name: Update Docker Hub Readme for dolt image
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          readme-filepath: ./docker/README.md
